version: '3.5'
services:
  db:
    container_name: db
    image: mysql
    # ports:
    #   - 3308:3306
    volumes:
      - ./db:/var/lib/mysql:bind
    environment:
      - MYSQL_ROOT_PASSWORD=xpzheng
      - MYSQL_DATABASE=hello
    command: --default-authentication-plugin=mysql_native_password
  redis:
    image: redis
    volumes:
      - ./redis-db:/data:bind
  server:
    container_name: server
    build:
      context: ./koa-app
    # ports:
    #   - 3000:3000
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
  web:
    container_name: web
    build:
      context: ./web-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:bind
    ports:
      - 80:80
    depends_on:
      - server
